version: "3.3"
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  ms:
    build: ../ms-tareas
    container_name: ms-tareas
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8081"

  bff:
    build: ../bff-tareas
    container_name: bff-tareas
    restart: always
    depends_on:
      - ms
    ports:
      - "8080:8080"
